name: Go

on:
  - push
  - pull_request

env:
  GO_VERSION: '^1.8.0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '${{ env.GO_VERSION }}'
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...
